Corrected the way load balancer proxy https requests to internal containers.

diff --git a/rootfs/etc/services.d/caddy-lb/run b/rootfs/etc/services.d/caddy-lb/run
--- a/rootfs/etc/services.d/caddy-lb/run
+++ b/rootfs/etc/services.d/caddy-lb/run
@@ -8,7 +8,30 @@ if [ -z "$DASPANEL_SYS_UUID" ]; then
     exit 1
 fi
 
-export DASPANEL_SYS_ADMIN=`cat /opt/daspanel/data/$DASPANEL_SYS_UUID/db/sysconfig.json | /usr/bin/jq -r '.sys.admin'`
+case "$DASPANEL_WAIT_FOR_API" in
+    YES|yes|Yes)
+        echo "[DASPANEL] Waiting 60 seconds for API: $0" >&2
+        /opt/daspanel/bin/wait-for-api -t 60 $DASPANEL_SYS_APISERVER/info/status
+        result=$?
+        if [ ! $result -eq 0 ] ; then
+            echo "[DASPANEL] Can not connect to API: $DASPANEL_SYS_APISERVER/info/status" >&2
+            exit 1
+        fi
+        ;;
+    *) 
+        echo "[DASPANEL] Container not need to wait API become online: $0" >&2
+        exit 1
+        ;;
+esac
+
+# Get system configs from API server and set env variables
+SYSCFG=$(wget -O- --header=Content-Type:application/json --header="Authorization: $DASPANEL_SYS_APIKEY" "$DASPANEL_SYS_APISERVER/tenants/$DASPANEL_SYS_UUID")
+result=$?
+if [ ! $result -eq 0 ] ; then
+    echo "[DASPANEL] Unable to get tenant configuration from API server: $0" >&2
+    exit 1
+fi
+export DASPANEL_SYS_ADMIN=`echo $SYSCFG | /usr/bin/jq -r '.sys.admin'`
 
 STARTCMD="su-exec daspanel:daspanel /usr/sbin/caddy --conf=/etc/caddy/caddyfile --log=stdout"
 #STARTCMD="/usr/sbin/caddy --conf=/etc/caddy/caddyfile"
