Removed dependence from daspanel/alpine-base.

diff --git a/rootfs/etc/cont-init.d/50-00-caddy-lb b/rootfs/etc/cont-init.d/50-00-caddy-lb
--- a/rootfs/etc/cont-init.d/50-00-caddy-lb
+++ b/rootfs/etc/cont-init.d/50-00-caddy-lb
@@ -1,25 +1,26 @@
 #!/usr/bin/with-contenv sh
 
+export DASPANEL_CONTAINER_TYPE="load-balancer-caddy"
+printf $DASPANEL_CONTAINER_TYPE > /var/run/s6/container_environment/DASPANEL_CONTAINER_TYPE
+
 # Installation UUID must be informed
 if [ -z "$DASPANEL_SYS_UUID" ]; then
-    echo "***"
-    echo "ERROR: You must set the env variable DASPANEL_SYS_UUID to a valid UUID"
-    echo "***"
+    echo "[DASPANEL-$DASPANEL_CONTAINER_TYPE] ERROR: You must set the env variable DASPANEL_SYS_UUID to a valid UUID"
     exit 1
 fi
 
 case "$DASPANEL_WAIT_FOR_API" in
     YES|yes|Yes)
-        echo "[DASPANEL] Waiting 60 seconds for API: $0" >&2
+        echo "[DASPANEL-$DASPANEL_CONTAINER_TYPE] Waiting 60 seconds for API: $0" >&2
         /opt/daspanel/bin/wait-for-api -t 60 $DASPANEL_SYS_APISERVER/info/status
         result=$?
         if [ ! $result -eq 0 ] ; then
-            echo "[DASPANEL] Can not connect to API: $DASPANEL_SYS_APISERVER/info/status" >&2
+            echo "[DASPANEL-$DASPANEL_CONTAINER_TYPE] Can not connect to API: $DASPANEL_SYS_APISERVER/info/status" >&2
             exit 1
         fi
         ;;
     *) 
-        echo "[DASPANEL] Container not need to wait API become online: $0" >&2
+        echo "[DASPANEL-$DASPANEL_CONTAINER_TYPE] Container not need to wait API become online: $0" >&2
         exit 1
         ;;
 esac
@@ -28,10 +29,10 @@ esac
 SYSCFG=$(wget -O- --header=Content-Type:application/json --header="Authorization: $DASPANEL_SYS_APIKEY" "$DASPANEL_SYS_APISERVER/tenants/$DASPANEL_SYS_UUID")
 result=$?
 if [ ! $result -eq 0 ] ; then
-    echo "[DASPANEL] Unable to get tenant configuration from API server: $0" >&2
+    echo "[DASPANEL-$DASPANEL_CONTAINER_TYPE] Unable to get tenant configuration from API server: $0" >&2
     exit 1
 fi
-export DASPANEL_SYS_HOSTNAME=`echo $SYSCFG | /usr/bin/jq -r '.sys.hostname'`
+export DASPANEL_SYS_HOSTNAME=`echo $SYSCFG | /opt/daspanel/bin/jq -r '.sys.hostname'`
 export ENGINE="load-balancer"
 
 if [ ! -d "/etc/caddy" ]; then
@@ -51,7 +52,7 @@ fi
 if [ ! -d "/opt/daspanel/data/$DASPANEL_SYS_UUID/certs/self/ca" ]; then
 	mkdir -p "/opt/daspanel/data/$DASPANEL_SYS_UUID/certs/self/ca"
 fi
-/usr/bin/gomplate -d cfg=$DASPANEL_SYS_APISERVER/tenants/$DASPANEL_SYS_UUID \
+/opt/daspanel/bin/gomplate -d cfg=$DASPANEL_SYS_APISERVER/tenants/$DASPANEL_SYS_UUID \
     -H "cfg=Authorization: $DASPANEL_SYS_APIKEY" \
     < /opt/daspanel/conf-templates/load-balancer/ssl/self-ca.cnf.tmpl \
     > /opt/daspanel/data/$DASPANEL_SYS_UUID/certs/self/ca/self-ca.cnf
@@ -63,7 +64,7 @@ fi
 /opt/daspanel/bin/load-balancer/gen-cert.sh $DASPANEL_SYS_HOSTNAME
 
 # Configure caddy
-/usr/bin/gomplate -d cfg=$DASPANEL_SYS_APISERVER/tenants/$DASPANEL_SYS_UUID \
+/opt/daspanel/bin/gomplate -d cfg=$DASPANEL_SYS_APISERVER/tenants/$DASPANEL_SYS_UUID \
     -H "cfg=Authorization: $DASPANEL_SYS_APIKEY" \
     < /opt/daspanel/conf-templates/load-balancer/caddy/caddyfile.tmpl \
     > /etc/caddy/caddyfile
diff --git a/rootfs/etc/services.d/caddy-lb/run b/rootfs/etc/services.d/caddy-lb/run
--- a/rootfs/etc/services.d/caddy-lb/run
+++ b/rootfs/etc/services.d/caddy-lb/run
@@ -2,24 +2,22 @@
 
 # Installation UUID must be informed
 if [ -z "$DASPANEL_SYS_UUID" ]; then
-    echo "***"
-    echo "ERROR: You must set the env variable DASPANEL_SYS_UUID to a valid UUID"
-    echo "***"
+    echo "[DASPANEL-$DASPANEL_CONTAINER_TYPE] ERROR: You must set the env variable DASPANEL_SYS_UUID to a valid UUID"
     exit 1
 fi
 
 case "$DASPANEL_WAIT_FOR_API" in
     YES|yes|Yes)
-        echo "[DASPANEL] Waiting 60 seconds for API: $0" >&2
+        echo "[DASPANEL-$DASPANEL_CONTAINER_TYPE] Waiting 60 seconds for API: $0" >&2
         /opt/daspanel/bin/wait-for-api -t 60 $DASPANEL_SYS_APISERVER/info/status
         result=$?
         if [ ! $result -eq 0 ] ; then
-            echo "[DASPANEL] Can not connect to API: $DASPANEL_SYS_APISERVER/info/status" >&2
+            echo "[DASPANEL-$DASPANEL_CONTAINER_TYPE] Can not connect to API: $DASPANEL_SYS_APISERVER/info/status" >&2
             exit 1
         fi
         ;;
     *) 
-        echo "[DASPANEL] Container not need to wait API become online: $0" >&2
+        echo "[DASPANEL-$DASPANEL_CONTAINER_TYPE] Container not need to wait API become online: $0" >&2
         exit 1
         ;;
 esac
@@ -28,13 +26,12 @@ esac
 SYSCFG=$(wget -O- --header=Content-Type:application/json --header="Authorization: $DASPANEL_SYS_APIKEY" "$DASPANEL_SYS_APISERVER/tenants/$DASPANEL_SYS_UUID")
 result=$?
 if [ ! $result -eq 0 ] ; then
-    echo "[DASPANEL] Unable to get tenant configuration from API server: $0" >&2
+    echo "[DASPANEL-$DASPANEL_CONTAINER_TYPE] Unable to get tenant configuration from API server: $0" >&2
     exit 1
 fi
-export DASPANEL_SYS_ADMIN=`echo $SYSCFG | /usr/bin/jq -r '.sys.admin'`
+export DASPANEL_SYS_ADMIN=`echo $SYSCFG | /opt/daspanel/bin/jq -r '.sys.admin'`
 
 STARTCMD="su-exec daspanel:daspanel /usr/sbin/caddy --conf=/etc/caddy/caddyfile --log=stdout"
-#STARTCMD="/usr/sbin/caddy --conf=/etc/caddy/caddyfile"
 
 [[ -z "${CADDY_AGREE}" ]] && CADDY_AGREE="true"
 [[ -z "${CADDY_CA}" ]] && CADDY_CA="https://acme-v01.api.letsencrypt.org/directory"
